name: dekaybaro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.7.7
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: 4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Sansation
      fonts:
        - asset: assets/fonts/Sansation_Bold_Italic.ttf
        - asset: assets/fonts/Sansation_Bold.ttf
        - asset: assets/fonts/Sansation_Italic.ttf
        - asset: assets/fonts/Sansation_Light_Italic.ttf
        - asset: assets/fonts/Sansation_Light.ttf
        - asset: assets/fonts/Sansation_Regular.ttf
          weight: 700
